# Generated by Django 4.1.7 on 2023-03-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlyTrucks', '0005_concesionaria_remolques'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Camion',
        ),
    ]
