# Generated by Django 4.1.7 on 2023-03-24 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlyTrucks', '0006_rename_post_camion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Concesionaria',
        ),
    ]
