# Generated by Django 4.1.7 on 2023-03-27 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlyTrucks', '0008_camion_vendedor_remolques_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='camiones'),
        ),
        migrations.AddField(
            model_name='remolques',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='remolques'),
        ),
    ]
