# Generated by Django 4.1.7 on 2023-03-27 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlyTrucks', '0009_camion_imagen_remolques_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remolques',
            old_name='Imagen',
            new_name='imagen',
        ),
    ]
