# Generated by Django 4.1.7 on 2023-03-27 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlyTrucks', '0010_rename_imagen_remolques_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remolques',
            old_name='imagen',
            new_name='Imagen',
        ),
    ]
